# Generated by Django 3.2 on 2021-04-20 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'barber_style_category',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('style_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='barber.stylecategory')),
            ],
            options={
                'db_table': 'barber_style_item',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='style/attachment')),
                ('style_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='barber.styleitem')),
            ],
            options={
                'db_table': 'barber_style_attachment',
                'abstract': False,
            },
        ),
    ]
