# Generated by Django 3.2 on 2021-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='images/user'),
        ),
    ]
